name: 'Bejewel Complete JIRA Tickets Reminder'
description: 'Send slack messages to remind complete JIRA tickets.'
inputs:
  webhook-url:
    description: 'Slack Webhook URL'
    required: true
  jira-slack-map:
    description: 'Map jira username to Slack member ID. ex: "spotlight21c:UBCDEFGHI,DavideViolante:UABCDEFGH"'
    required: true
  jira-api-url:
    description: 'Jira API URL'
    required: true
  jira-user-email:
    description: 'Jira User Email'
    required: true
  jira-api-token:
    description: 'Jira API Token'
    required: true
  target-tickets:
    description: 'target tickets. ex: "ABC-123,DEF-456,ZXC-789"'
    required: true
  slack-channel:
    description: 'Slack Channel'
    required: true
  slack-bot-name:
    description: 'Slack Bot Name'
    required: true
  slack-icon-emoji:
    description: 'Slack Icon Emoji'
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'
